### ISSUE TITLE
Setup authentication via OnlineWeb using OAuth/OIDC

### ISSUE THREAD

**Issue by Endremgs** [appKom/OnlineOpptak#12]
Check readme in
https://github.com/dotkom/onlineweb4

### Client from dotkom
Redirect url = "https://online-opptak.vercel.app/form"
Client ID = "627450"
response type = "code"

This gives access to this api: https://old.online.ntnu.no/api/v1/

The following endpoints are interesting: 
https://old.online.ntnu.no/api/v1/profile/ 
- email
- telephone number
- userid
- is_commitee

### How to check commitee membership
Userid can be used to fetch committee member id from https://old.online.ntnu.no/api/v1/group/members

check if committee member id is contained in members array in a group at https://old.online.ntnu.no/api/v1/group/online-groups/

### Library to use for authorization
- https://next-auth.js.org/

**Comment by julian-ao** [comment]
https://next-auth.js.org/configuration/providers/oauth#using-a-custom-provider
